const projectDesktopAPI = [
  {
    id: 1,
    name: "Flower Shop",
    subname: "Responsive Django and React.js Flower Shop",
    videoDesktop: "https://www.youtube.com/embed/6lSn6Rup8RA",
    videoTablet: "https://www.youtube.com/embed/0L4KcNIj9NM",
    videoMobile: "https://www.youtube.com/embed/GG-pj3ttzOk",
    date: "12/2023 – 02/2024",
    description:
      "Welcome to our delightful Online Flower Shop, where the process of selecting and ordering your favorite flowers is made effortless. Leveraging the powerful combination of Django and React JS, we've crafted a user-friendly website that ensures a seamless and enjoyable experience for our customers.",
    imagecharacter: "flower-shop.png",
    imagesDesktop: [
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/10.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/11.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/12.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/13.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/14.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/15.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/16.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/17.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/18.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/19.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/20.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/21.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/22.png",
    ],
    imagesTablet: [
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/10.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/11.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/12.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/13.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/14.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/15.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/16.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/17.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/18.png",
    ],
    imagesMobile: [
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/10.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/11.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/12.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/13.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/14.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/15.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/16.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/17.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/18.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/19.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/20.png",
    ],
  },
  {
    id: 2,
    name: "Organic Fruits Website",
    subname: "Responsive HTML, CSS & JS Website",
    videoDesktop: "https://www.youtube.com/embed/6lSn6Rup8RA",
    videoTablet: "https://www.youtube.com/embed/0L4KcNIj9NM",
    videoMobile: "https://www.youtube.com/embed/GG-pj3ttzOk",
    date: "11/2023",
    description:
      "Dive into the freshness of nature with our Organic Fruits and Vegetables website template. Crafted using HTML, CSS, Bootstrap, and JavaScript, it's a simple yet vibrant multipage design. Whether you're on a computer, tablet, or phone, the responsive layout ensures a seamless browsing experience. Explore the pages effortlessly and savor the simplicity of nature's bounty.",
    imagecharacter: "Organic-Fruits-Website.png",
    imagesDesktop: [
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/10.png",
    ],
    imagesTablet: [
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/10.png",
    ],
    imagesMobile: [
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/10.png",
    ],
  },
  {
    id: 3,
    name: "G&C Organics",
    subname: "Responsive HTML, CSS & JS Website",
    videoDesktop: "https://www.youtube.com/embed/hX8uTLe7jko",
    videoTablet: "https://www.youtube.com/embed/_4Q1Y_nLwNc",
    videoMobile: "https://www.youtube.com/embed/tDWwCz6zAOw",
    date: "10/2023",
    description:
      "Introducing G&C Organics - a single-page haven for organic enthusiasts. Crafted with HTML, CSS, and Bootstrap, this website is a sleek showcase of purity. Navigate seamlessly through our offerings, from organic produce to eco-friendly goods. The minimalist design ensures a delightful user experience. Dive into G&C Organics - where simplicity meets sustainability.",
    imagecharacter: "G-and-C.png",
    imagesDesktop: [
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/10.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/11.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/12.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/13.png",
      "Images/Projects/FlowerShop/FlowerShop-Desktop-SS/14.png",
    ],
    imagesTablet: [
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/10.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/11.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/12.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/13.png",
      "Images/Projects/FlowerShop/FlowerShop-Tablet-SS/14.png",
    ],
    imagesMobile: [
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/1.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/2.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/3.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/4.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/5.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/6.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/7.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/8.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/9.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/10.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/11.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/12.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/13.png",
      "Images/Projects/FlowerShop/FlowerShop-Mobile-SS/14.png",
    ],
    link: "https://govindchoudhary844.github.io/G-C-Organics/",
  },
];

export default projectDesktopAPI;
