const ProjectDesktop = [
  {
    id: 1,
    name: "Flower Shop",
    video: "Images/Projects/Project 1/Project1-Desktop.mp4",
    description:
      "Welcome to our delightful Online Flower Shop, where the process of selecting and ordering your favorite flowers is made effortless. Leveraging the powerful combination of Django and React JS, we've crafted a user-friendly website that ensures a seamless and enjoyable experience for our customers.",
    images: [
      "Images/Projects/Project 1/Project1-Desktop-SS/1.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/2.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/3.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/4.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/5.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/6.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/7.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/8.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/9.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/10.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/11.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/12.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/13.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/14.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/15.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/16.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/17.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/18.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/19.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/20.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/21.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/22.png",
    ],
  },
  {
    id: 2,
    name: "Organic Fruits Website",
    video: "Images/Projects/Project 1/Project1-Desktop.mp4",
    description:
      "Dive into the freshness of nature with our Organic Fruits and Vegetables website template. Crafted using HTML, CSS, Bootstrap, and JavaScript, it's a simple yet vibrant multipage design. Whether you're on a computer, tablet, or phone, the responsive layout ensures a seamless browsing experience. Explore the pages effortlessly and savor the simplicity of nature's bounty.",
    images: [
      "Images/Projects/Project 1/Project1-Desktop-SS/1.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/2.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/3.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/4.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/5.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/6.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/7.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/8.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/9.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/10.png",
    ],
  },
  {
    id: 3,
    name: "G&C Organics",
    video: "Images/Projects/Project 1/Project1-Desktop.mp4",
    description:
      "Introducing G&C Organics - a single-page haven for organic enthusiasts. Crafted with HTML, CSS, and Bootstrap, this website is a sleek showcase of purity. Navigate seamlessly through our offerings, from organic produce to eco-friendly goods. The minimalist design ensures a delightful user experience. Dive into G&C Organics - where simplicity meets sustainability.",
    images: [
      "Images/Projects/Project 1/Project1-Desktop-SS/1.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/2.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/3.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/4.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/5.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/6.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/7.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/8.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/9.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/10.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/11.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/12.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/13.png",
      "Images/Projects/Project 1/Project1-Desktop-SS/14.png",
    ],
  },
];

export default ProjectDesktop;
